version: "3.8"

services:
  backend:
    build: .
    container_name: mobilecoder-backend
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: mobilecoder-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    restart: always
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3001:3000"
    # environment:
    #   - GF_SERVER_ROOT_URL=https://api.mobilecoder.shop/grafana/
    #   - GF_SERVER_SERVE_FROM_SUB_PATH=true

  pgadmin:
    image: dpage/pgadmin4
    container_name: mobilecoder-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mobilecoder.shop
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
